[package]
name = "stroke_contrast"
version = "0.1.0"
edition = "2024"

[dependencies]
harfruzz = "0.1.0"
kurbo = "0.11.2"
clap = { version = "4.5.37", features = ["derive"] }
home-dir = "0.1.0"
skrifa = "0.31.3"
